### ISSUE TITLE
Typescript

### ISSUE THREAD

**Issue by tomitrescak** [skolmer/vscode-i18n-tag-schema#2]
Hi, fantastic work! would you consider supporting typescript? Currently it requires only JS files. Thanks!

**Comment by skolmer** [comment]
Thank you! 
I have moved your feature request to the following repo: https://github.com/skolmer/i18n-tag-schema/issues/8

**Comment by skolmer** [comment]
https://github.com/skolmer/vscode-i18n-tag-schema/releases/tag/v2.1.0
